In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.15.0


In [ ]:
#create a constant tensor A

A = tf.constant([[4,3],[6,1]]) #constant
print(A)

tf.Tensor(
[[4 3]
 [6 1]], shape=(2, 2), dtype=int32)


In [ ]:
#create a variable tensor V

V = tf.Variable([[1,2,3],[4,5,6]]) #Variable
print(V)
B = tf.constant([[5,8],[9,5]]) #constant
print(B)


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
tf.Tensor(
[[5 8]
 [9 5]], shape=(2, 2), dtype=int32)


In [ ]:
#concatenate

AB = tf.concat([A,B],0)
print(AB)

tf.Tensor(
[[4 3]
 [6 1]
 [5 8]
 [9 5]], shape=(4, 2), dtype=int32)


In [ ]:
  tensor = tf.zeros([2,3])
  print(tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
  tensor = tf.ones([2,3])
  print(tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
tensor = tf.eye(3)
print(tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
tensor = tf.random.normal([2,3])
print(tensor)

tf.Tensor(
[[-0.31467777  0.04405714 -0.15871798]
 [ 1.3451847  -0.10027208 -0.6462064 ]], shape=(2, 3), dtype=float32)


In [ ]:
tensor = tf.random.uniform([2,3])
print(tensor)

tf.Tensor(
[[0.6138401  0.83335245 0.61156285]
 [0.5994549  0.9080287  0.35594296]], shape=(2, 3), dtype=float32)


In [ ]:
shape = tf.reshape(tensor,[3,2])

In [ ]:
#typecast

tensor=tf.constant([[1.8,2.3],
                   [4.2,5.5],
                   [5.2,9.0],
                   [7.1,2.5]],
                   dtype=tf.float32)
print(tensor)
casted_tensor = tf.cast(tensor,dtype=tf.int32)
print(casted_tensor)

tf.Tensor(
[[1.8 2.3]
 [4.2 5.5]
 [5.2 9. ]
 [7.1 2.5]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[1 2]
 [4 5]
 [5 9]
 [7 2]], shape=(4, 2), dtype=int32)


In [ ]:
a=tf.transpose(tensor)
print(a)

tf.Tensor(
[[1.8 4.2 5.2 7.1]
 [2.3 5.5 9.  2.5]], shape=(2, 4), dtype=float32)


In [ ]:
a= tf.constant([[1,2],[4,5]])

v = tf.constant([[5],
                [6]])

av = tf.matmul(a,v)
print(av)


tf.Tensor(
[[17]
 [50]], shape=(2, 1), dtype=int32)


In [ ]:
av = tf.multiply(a,v)
print(av)

tf.Tensor(
[[ 5 10]
 [24 30]], shape=(2, 2), dtype=int32)


In [1]:
import datetime, warnings,scipy
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.style.use("fivethirtyeight")
mpl.rcParams["patch.force_edgecolor"] = True
warnings.filterwarnings("ignore")
%matplotlib inline
mpl.rc('patch',edgecolor='black',linewidth=1)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
pd.set_option('display.max_columns',None)

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.48895955, -0.2060877 , -0.04512563,  0.28095743, -0.15199111,
        -0.3010535 ,  0.05707809, -0.3373923 ,  0.3242361 ,  0.29012412]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.1507651 , 0.07523946, 0.0883793 , 0.12245223, 0.07942176,
        0.06842306, 0.09788972, 0.06598129, 0.12786813, 0.12357987]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.6820455

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2939 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1396 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1069 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0854 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0734 - accuracy: 0.9766


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0728 - accuracy: 0.9770 - 568ms/epoch - 2ms/step


[0.07284731417894363, 0.9769999980926514]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.6525580e-08, 6.8419830e-08, 1.3385775e-05, 3.8034844e-04,
        5.3927046e-10, 1.0284947e-06, 4.9085231e-13, 9.9960071e-01,
        1.4282972e-07, 4.2602164e-06],
       [1.0641706e-08, 2.1432564e-04, 9.9978381e-01, 1.4208855e-06,
        8.1959488e-13, 1.5254282e-07, 2.2817845e-08, 1.7940839e-12,
        3.3090734e-07, 1.6817572e-12],
       [5.6536042e-08, 9.9908245e-01, 4.7488484e-05, 3.7865216e-06,
        2.4041998e-05, 9.8663031e-07, 8.2681499e-06, 7.8303827e-04,
        4.8903967e-05, 1.1678907e-06],
       [9.9991667e-01, 4.3672284e-09, 3.7177684e-05, 4.6746985e-07,
        1.9392272e-07, 1.7034616e-05, 6.3029524e-06, 1.6861175e-05,
        4.6447292e-07, 4.7341869e-06],
       [6.4956072e-07, 8.9029828e-10, 2.7677966e-06, 2.2362395e-08,
        9.9817979e-01, 1.5586141e-07, 2.4197625e-06, 1.4575302e-05,
        6.9874756e-07, 1.7989199e-03]], dtype=float32)>